# Makefile for TCP Proxy Server

CXX = g++
CXXFLAGS = -Wall -Wextra -pedantic -O3
LDFLAGS = -lpthread

TARGET = tcpproxy_server
SRCS = tcpproxy_server.cpp

all: $(TARGET)

$(TARGET): $(SRCS)
    $(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS) $(LDFLAGS)

clean:
    rm -f $(TARGET)
